apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lead-scoring.fullname" . }}
  labels: {{- include "lead-scoring.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels: {{- include "lead-scoring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "lead-scoring.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "lead-scoring.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef: { name: {{ include "lead-scoring.fullname" . }}-config }
          startupProbe:
            httpGet: { path: {{ .Values.probes.startup.path }}, port: {{ .Values.service.targetPort }} }
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          livenessProbe:
            httpGet: { path: {{ .Values.probes.liveness.path }}, port: {{ .Values.service.targetPort }} }
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet: { path: {{ .Values.probes.readiness.path }}, port: {{ .Values.service.targetPort }} }
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
