apiVersion: v1
kind: Secret
metadata:
  name: salespipe-secret
  namespace: salespipe
type: Opaque
stringData:
  DB_PASSWORD: salespipe
  JWT_SECRET: k8s-secret-min-256-bits-long-for-hs256-xxxxxxxxxxxxxxxxxxxxx
