apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "salespipe.fullname" . }}-config
  labels: {{- include "salespipe.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
